# daQ – Data Quality Vocabulary
#
# Authors:
# Christoph Lange <math.semantic.web@gmail.com>
# Jeremy Debattista <jerdebattista@gmail.com>
#
# © 2014–

PREFIX = ..

include $(PREFIX)/Makefile.vars

all: dqm.rdf

include $(PREFIX)/Makefile.in
