/* CVS $Id: $ */
package de.unibonn.iai.eis.luzzu.semantics.vocabularies; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from src/main/resources/vocabularies/qr/qr.trig 
 * @author Auto-generated by schemagen on 13 Jul 2014 03:54 
 */
public class QR {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/eis/vocab/qr#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>Represents the dataset URI on which quality metrics where computed</p> */
    public static final Property computedOn = m_model.createProperty( "http://purl.org/eis/vocab/qr#computedOn" );
    
    /** <p>Identifies problem instances in the report</p> */
    public static final Property hasProblem = m_model.createProperty( "http://purl.org/eis/vocab/qr#hasProblem" );
    
    /** <p>Represent the URI of the metric which instantiated this problem</p> */
    public static final Property isDescribedBy = m_model.createProperty( "http://purl.org/eis/vocab/qr#isDescribedBy" );
    
    /** <p>Contains brief summary of the quality problem that is presented to the user.</p> */
    public static final Property problemDescription = m_model.createProperty( "http://purl.org/eis/vocab/qr#problemDescription" );
    
    /** <p>Represent the actual problematic instance from the dataset. This could be 
     *  a list of resources (rdf:Seq) or a list of reified statements.</p>
     */
    public static final Property problematicThing = m_model.createProperty( "http://purl.org/eis/vocab/qr#problematicThing" );
    
    /** <p>Contains recommendation of how to solve the corresponding quality problem.</p> */
    public static final Property recommedation = m_model.createProperty( "http://purl.org/eis/vocab/qr#recommedation" );
    
    /** <p>Represents a kind of quality problems in which blank nodes are used in subject 
     *  or object position.</p>
     */
    public static final Resource BlankNodeUsageProblem = m_model.createResource( "http://purl.org/eis/vocab/qr#BlankNodeUsageProblem" );
    
    /** <p>Represents recommendation for how to solve the corresponding quality problem.</p> */
    public static final Resource CleaningRecommendation = m_model.createResource( "http://purl.org/eis/vocab/qr#CleaningRecommendation" );
    
    /** <p>Identifies when an ontology author is not defined.</p> */
    public static final Resource DefinedOntologyAuthorProblem = m_model.createResource( "http://purl.org/eis/vocab/qr#DefinedOntologyAuthorProblem" );
    
    /** <p>Represents a kind of quality problems in which literal value in annotation 
     *  property is empty.</p>
     */
    public static final Resource EmptyAnnotationValueProblem = m_model.createResource( "http://purl.org/eis/vocab/qr#EmptyAnnotationValueProblem" );
    
    /** <p>Represents a kind of quality problems in which data type are not homogeneous</p> */
    public static final Resource HomogeneousDatatypesProblem = m_model.createResource( "http://purl.org/eis/vocab/qr#HomogeneousDatatypesProblem" );
    
    /** <p>Represents a kind of quality problems in which literal value is not consistent 
     *  with data type defined by property range</p>
     */
    public static final Resource IncompatibleDatatypeRangeProblem = m_model.createResource( "http://purl.org/eis/vocab/qr#IncompatibleDatatypeRangeProblem" );
    
    /** <p>Represents a kind of quality problems in which object value in label property 
     *  uses a bad style of capitalization.</p>
     */
    public static final Resource LabelsUsingCapitalsProblem = m_model.createResource( "http://purl.org/eis/vocab/qr#LabelsUsingCapitalsProblem" );
    
    /** <p>Represents a kind of quality problems in which literal value is not consistent 
     *  with defined data type</p>
     */
    public static final Resource MalformedDatatypeLiteralsProblem = m_model.createResource( "http://purl.org/eis/vocab/qr#MalformedDatatypeLiteralsProblem" );
    
    /** <p>Represents a kind of quality problems in which classes or properties are not 
     *  places properly.</p>
     */
    public static final Resource MisplacedClassesOrPropertiesProblem = m_model.createResource( "http://purl.org/eis/vocab/qr#MisplacedClassesOrPropertiesProblem" );
    
    /** <p>Represents a kind of quality problems in which owl classes or owl properties 
     *  are not used properly.</p>
     */
    public static final Resource MisuseOwlDatatypeOrObjectPropertiesProblem = m_model.createResource( "http://purl.org/eis/vocab/qr#MisuseOwlDatatypeOrObjectPropertiesProblem" );
    
    /** <p>Represents a quality problem detected during the assessment of quality metrics 
     *  on triples.</p>
     */
    public static final Resource QualityProblem = m_model.createResource( "http://purl.org/eis/vocab/qr#QualityProblem" );
    
    /** <p>Represents a report on the problems detected during the assessment of quality 
     *  on a dataset.</p>
     */
    public static final Resource QualityReport = m_model.createResource( "http://purl.org/eis/vocab/qr#QualityReport" );
    
    /** <p>Represents a kind of quality problems when RDF can not be accessed.</p> */
    public static final Resource RDFAccessibilityProblem = m_model.createResource( "http://purl.org/eis/vocab/qr#RDFAccessibilityProblem" );
    
    /** <p>Represents a kind of quality problems when SPARQL Endpoint can not be accessed.</p> */
    public static final Resource SPARQLAccessibilityProblem = m_model.createResource( "http://purl.org/eis/vocab/qr#SPARQLAccessibilityProblem" );
    
    /** <p>Represents a kind of quality problems in which classes are not defined</p> */
    public static final Resource UndefinedClassesProblem = m_model.createResource( "http://purl.org/eis/vocab/qr#UndefinedClassesProblem" );
    
    /** <p>Represents a kind of quality problems in which classes or properties are not 
     *  defined</p>
     */
    public static final Resource UndefinedPropertiesProblem = m_model.createResource( "http://purl.org/eis/vocab/qr#UndefinedPropertiesProblem" );
    
    /** <p>Represents a kind of quality problems in which object in annotation property 
     *  contains white spaces.</p>
     */
    public static final Resource WhitespaceInAnnotationProblem = m_model.createResource( "http://purl.org/eis/vocab/qr#WhitespaceInAnnotationProblem" );
    
}
