PREFIX daq:<http://purl.org/eis/vocab/daq#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?category_name ?dimension_name ?metric_name ?metric ?metric_uri
WHERE {
	?metric a ?metric_uri .
	?metric_uri rdfs:subClassOf daq:Metric .
	?has_dimension_metric rdfs:range ?metric_uri .
	?has_dimension_metric rdfs:domain ?dimension_uri .
	?has_category_dim rdfs:range ?dimension_uri .
	?has_category_dim rdfs:domain ?category_uri .
	OPTIONAL { ?category_uri rdfs:label ?category_name } .
	OPTIONAL { ?dimension_uri rdfs:label ?dimension_name } .
	OPTIONAL { ?metric_uri rdfs:label ?metric_name } .
} 
		