/* Generated By:JavaCC: Do not edit this line. LQMLParserConstants.java */
package de.unibonn.iai.eis.luzzu.qml.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LQMLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DEF = 5;
  /** RegularExpression Id. */
  int LABEL = 6;
  /** RegularExpression Id. */
  int DESC = 7;
  /** RegularExpression Id. */
  int RULE = 8;
  /** RegularExpression Id. */
  int ACTION = 9;
  /** RegularExpression Id. */
  int METRICURI = 10;
  /** RegularExpression Id. */
  int AUTHOR = 11;
  /** RegularExpression Id. */
  int PACKAGE = 12;
  /** RegularExpression Id. */
  int TYPEOF = 13;
  /** RegularExpression Id. */
  int COUNT = 14;
  /** RegularExpression Id. */
  int MAP = 15;
  /** RegularExpression Id. */
  int CHAR = 16;
  /** RegularExpression Id. */
  int NUMBER = 17;
  /** RegularExpression Id. */
  int STRICT_STR = 18;
  /** RegularExpression Id. */
  int STR = 19;
  /** RegularExpression Id. */
  int QUOTED_STR = 20;
  /** RegularExpression Id. */
  int LBRACE = 21;
  /** RegularExpression Id. */
  int RBRACE = 22;
  /** RegularExpression Id. */
  int LPAREN = 23;
  /** RegularExpression Id. */
  int RPAREN = 24;
  /** RegularExpression Id. */
  int COLON = 25;
  /** RegularExpression Id. */
  int SEMI_COLON = 26;
  /** RegularExpression Id. */
  int PERIOD = 27;
  /** RegularExpression Id. */
  int QUOTES = 28;
  /** RegularExpression Id. */
  int BOOLEAN_OPERATOR = 29;
  /** RegularExpression Id. */
  int EQ = 30;
  /** RegularExpression Id. */
  int NEQ = 31;
  /** RegularExpression Id. */
  int LT = 32;
  /** RegularExpression Id. */
  int GT = 33;
  /** RegularExpression Id. */
  int LTE = 34;
  /** RegularExpression Id. */
  int GTE = 35;
  /** RegularExpression Id. */
  int LOGICAL_OPERATOR = 36;
  /** RegularExpression Id. */
  int HEADER_INDICATOR = 37;
  /** RegularExpression Id. */
  int SUBJECT_VAR = 38;
  /** RegularExpression Id. */
  int PREDICATE_VAR = 39;
  /** RegularExpression Id. */
  int OBJECT_VAR = 40;
  /** RegularExpression Id. */
  int IRIref = 41;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"def\"",
    "\"label\"",
    "\"description\"",
    "\"rule\"",
    "\"action\"",
    "\"metric\"",
    "\"author\"",
    "\"package\"",
    "\"typeof\"",
    "\"count\"",
    "\"map\"",
    "<CHAR>",
    "<NUMBER>",
    "<STRICT_STR>",
    "<STR>",
    "<QUOTED_STR>",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\":\"",
    "\";\"",
    "\".\"",
    "\"\\\"\"",
    "<BOOLEAN_OPERATOR>",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "<LOGICAL_OPERATOR>",
    "\"%%\"",
    "\"?s\"",
    "\"?p\"",
    "\"?o\"",
    "<IRIref>",
  };

}
