/* Generated By:JavaCC: Do not edit this line. LQMLParser.java */
package de.unibonn.iai.eis.luzzu.qml.parser;

import java.io.Reader ;
import java.io.StringReader ;

import java.util.ArrayList;
import java.util.List;
import java.util.Map ;
import java.util.HashMap ;

import de.unibonn.iai.eis.luzzu.qml.datatypes.Condition;
import de.unibonn.iai.eis.luzzu.qml.datatypes.ConditionType;
import de.unibonn.iai.eis.luzzu.qml.datatypes.Metric;
import de.unibonn.iai.eis.luzzu.qml.datatypes.Action;
import de.unibonn.iai.eis.luzzu.qml.datatypes.Rule;

public class LQMLParser implements LQMLParserConstants {
  static Map<String,String> compilerMap;

// BNF Definition  final public Map<String,String> parse() throws ParseException {
 compilerMap = new HashMap<String,String>();
    extractHeader();
   compilerMap.put("[%%classname%%]",extractDefinitionName());
   compilerMap.put("[%%metricuri%%]",extractMetricURI());
   compilerMap.put("[%%label%%]",extractLabel());
   compilerMap.put("[%%description%%]",extractDescription());
    Rule r = extractRule();
        Action a = extractAction();
        Metric metric = new Metric(r, a);
        {compilerMap.put("[%%computefunction%%]",metric.getComputeFunction());}
        {compilerMap.put("[%%imports%%]",metric.getImports());}
        {compilerMap.put("[%%variables%%]",metric.getVariables());}
        {compilerMap.put("[%%metricvaluefuntion%%]",metric.actionToJava());}
    jj_consume_token(PERIOD);
    jj_consume_token(0);
   {if (true) return compilerMap;}
    throw new Error("Missing return statement in function");
  }

  final public void extractHeader() throws ParseException {
    compilerMap.put("[%%author%%]",extractAuthor());
    compilerMap.put("[%%packagename%%]",extractPackage());
  }

  final public String extractAuthor() throws ParseException {
  Token t;
  String author = "";
    jj_consume_token(HEADER_INDICATOR);
    jj_consume_token(AUTHOR);
    jj_consume_token(COLON);
    t = jj_consume_token(QUOTED_STR);
  author = t.image.replace("\u005c"","") ;
  {if (true) return author;}
    throw new Error("Missing return statement in function");
  }

  final public String extractPackage() throws ParseException {
  Token t;
  String pkg = "";
    jj_consume_token(HEADER_INDICATOR);
    jj_consume_token(PACKAGE);
    jj_consume_token(COLON);
    t = jj_consume_token(QUOTED_STR);
          pkg = t.image.replace("\u005c"","")  ;
          {if (true) return pkg;}
    throw new Error("Missing return statement in function");
  }

  final public String extractDefinitionName() throws ParseException {
  Token t;
    jj_consume_token(DEF);
    jj_consume_token(LBRACE);
    t = jj_consume_token(STRICT_STR);
         String s = t.image.replace("\u005c"","") ;
    jj_consume_token(RBRACE);
    jj_consume_token(COLON);
         {if (true) return s;}
    throw new Error("Missing return statement in function");
  }

  final public String extractLabel() throws ParseException {
  Token t;
    jj_consume_token(LABEL);
    jj_consume_token(LBRACE);
    t = jj_consume_token(QUOTED_STR);
          String s = t.image.replace("\u005c"","") ;
    jj_consume_token(RBRACE);
    jj_consume_token(SEMI_COLON);
         {if (true) return s;}
    throw new Error("Missing return statement in function");
  }

  final public String extractDescription() throws ParseException {
  Token t;
    jj_consume_token(DESC);
    jj_consume_token(LBRACE);
    t = jj_consume_token(QUOTED_STR);
          String s = t.image;
    jj_consume_token(RBRACE);
    jj_consume_token(SEMI_COLON);
         {if (true) return s;}
    throw new Error("Missing return statement in function");
  }

  final public Rule extractRule() throws ParseException {
  Rule r = new Rule();
  List<ArrayList<Condition>> conditionList = new ArrayList<ArrayList<Condition>>();
    jj_consume_token(MATCH);
    jj_consume_token(LBRACE);
         ArrayList<Condition> condLst = new ArrayList<Condition>();
    extractCondition(condLst);
         conditionList.add(condLst);
    jj_consume_token(RBRACE);
    jj_consume_token(SEMI_COLON);
         r.setConditionList(conditionList);
         {if (true) return r;}
    throw new Error("Missing return statement in function");
  }

  final public void extractCondition(ArrayList<Condition> condLst) throws ParseException {
  Token t;
    jj_consume_token(LPAREN);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LPAREN:
      jj_consume_token(LPAREN);
      t = jj_consume_token(TYPEOF);
     condLst.add(extractTypeOf());
      jj_consume_token(RPAREN);
      break;
    default:
      jj_la1[0] = jj_gen;
     condLst.add(extractNonDefinedCondition());
    }
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LOGICAL_OPERATOR:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
      jj_consume_token(LOGICAL_OPERATOR);
      extractCondition(condLst);
    }
    jj_consume_token(RPAREN);
  }

  final public Condition extractTypeOf() throws ParseException {
  Token t;
  Condition c = new Condition();
    jj_consume_token(LPAREN);
    jj_consume_token(SUBJECT_VAR);
    jj_consume_token(RPAREN);
    t = jj_consume_token(BOOLEAN_OPERATOR);
         c.setBooleanOperator(t.image);
    t = jj_consume_token(IRIref);
                c.setConditionType(ConditionType.TYPEOF);
                c.setRhs(t.image);
                {if (true) return c;}
    throw new Error("Missing return statement in function");
  }

  final public Condition extractNonDefinedCondition() throws ParseException {
  Token t, t2, t3;
  Condition c = new Condition();
  c.setConditionType(ConditionType.NORMAL);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SUBJECT_VAR:
      t = jj_consume_token(SUBJECT_VAR);
            c.setLhs("?s");
      t2 = jj_consume_token(BOOLEAN_OPERATOR);
      t3 = jj_consume_token(IRIref);
      break;
    case PREDICATE_VAR:
      t = jj_consume_token(PREDICATE_VAR);
          c.setLhs("?p");
      t2 = jj_consume_token(BOOLEAN_OPERATOR);
      t3 = jj_consume_token(IRIref);
      break;
    case OBJECT_VAR:
      t = jj_consume_token(OBJECT_VAR);
                    c.setLhs("?o");
      t2 = jj_consume_token(BOOLEAN_OPERATOR);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IRIref:
        t3 = jj_consume_token(IRIref);
        break;
      case QUOTED_STR:
        t3 = jj_consume_token(QUOTED_STR);
        break;
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
          c.setBooleanOperator(t2.image);
        c.setRhs(t3.image);
          {if (true) return c;}
    throw new Error("Missing return statement in function");
  }

  final public Action extractAction() throws ParseException {
  Token t;
  Action action;
    jj_consume_token(ACTION);
    jj_consume_token(LBRACE);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MAP:
      jj_consume_token(MAP);
                 action = Action.MAP;
      break;
    case COUNT:
      jj_consume_token(COUNT);
                   action = Action.COUNT;
      break;
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(RBRACE);
    {if (true) return action;}
    throw new Error("Missing return statement in function");
  }

  final public String extractMetricURI() throws ParseException {
        Token t;
    jj_consume_token(METRICURI);
    jj_consume_token(LBRACE);
    t = jj_consume_token(IRIref);
   String s = t.image.replace("<","").replace(">","") ;
    jj_consume_token(RBRACE);
    jj_consume_token(SEMI_COLON);
   {if (true) return s;}
    throw new Error("Missing return statement in function");
  }

  /** Generated Token Manager. */
  public LQMLParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[5];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x1000000,0x0,0x200000,0x0,0x18000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x20,0x400,0x380,0x0,};
   }

  /** Constructor with InputStream. */
  public LQMLParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public LQMLParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new LQMLParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public LQMLParser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new LQMLParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public LQMLParser(LQMLParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(LQMLParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[43];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 5; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 43; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
